                /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author ACER
 */
public class MenuAdmin extends javax.swing.JFrame {
    int mousexdrag;
    int mouseydrag;
    
    
       
    MenuAdmin(String C) {
       initComponents();
       Name.setText(C);
       setIcon();
    }
  
   Settings A = new Settings();
   AddPeople B = new AddPeople();
   AddTeacher C = new AddTeacher();
   AddStudent D = new AddStudent();
   Grafik E = new Grafik();
   Profile F = new Profile();
    
    
    public void LB1(){
        LB2.setForeground(new Color(0,102,204));
        LB3.setForeground(new Color(0,102,204));
        LB4.setForeground(new Color(0,102,204));
        LB5.setForeground(new Color(0,102,204));
        LB6.setForeground(new Color(0,102,204));
    }
    
    public void LB2(){
        LB1.setForeground(new Color(0,102,204));
        LB3.setForeground(new Color(0,102,204));
        LB4.setForeground(new Color(0,102,204));
        LB5.setForeground(new Color(0,102,204));
        LB6.setForeground(new Color(0,102,204));
    }
    
    public void LB3(){
        LB2.setForeground(new Color(0,102,204));
        LB1.setForeground(new Color(0,102,204));
        LB4.setForeground(new Color(0,102,204));
        LB5.setForeground(new Color(0,102,204));
        LB6.setForeground(new Color(0,102,204));
    }
    
    public void LB4(){
        LB2.setForeground(new Color(0,102,204));
        LB3.setForeground(new Color(0,102,204));
        LB1.setForeground(new Color(0,102,204));
        LB5.setForeground(new Color(0,102,204));
        LB6.setForeground(new Color(0,102,204));
    }
    public void LB5(){
        LB2.setForeground(new Color(0,102,204));
        LB3.setForeground(new Color(0,102,204));
        LB4.setForeground(new Color(0,102,204));
        LB1.setForeground(new Color(0,102,204));
        LB6.setForeground(new Color(0,102,204));
    }
    
    public void LB6(){
        LB2.setForeground(new Color(0,102,204));
        LB3.setForeground(new Color(0,102,204));
        LB4.setForeground(new Color(0,102,204));
        LB5.setForeground(new Color(0,102,204));
        LB1.setForeground(new Color(0,102,204));
    }

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LBL = new javax.swing.JLabel();
        Fields = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Out = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Buttons3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        LB4 = new javax.swing.JLabel();
        Buttons4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        LB1 = new javax.swing.JLabel();
        Buttons5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        LB2 = new javax.swing.JLabel();
        Buttons6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        LB5 = new javax.swing.JLabel();
        Buttons7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        LB3 = new javax.swing.JLabel();
        Buttons8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        LB6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Admin - SMI version 1.0 BETA");
        setUndecorated(true);
        setResizable(false);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_close_window_30px_9.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_minimize_window_30px_1.png"))); // NOI18N
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_news_20px.png"))); // NOI18N
        jLabel1.setText(" Menu Admin - SMI version 1.0 BETA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(Minimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(925, 170));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_news_90px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SCHOOL MANAGEMENT INFORMATION");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Create Your Information with Us");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Version 1.0 BETA");

        LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_search_40px_2.png"))); // NOI18N

        Fields.setBackground(new java.awt.Color(0, 102, 204));
        Fields.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Fields.setForeground(new java.awt.Color(255, 255, 255));
        Fields.setBorder(null);
        Fields.setCaretColor(new java.awt.Color(255, 255, 255));
        Fields.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_admin_settings_male_90px.png"))); // NOI18N

        Name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("DWI RIFKI NOVIANTO");

        Out.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Out.setForeground(new java.awt.Color(255, 255, 255));
        Out.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Out.setText("LOG OUT");
        Out.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OutMouseExited(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CARI");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(Fields, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Out, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Name))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LBL)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Fields, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Out)
                .addGap(25, 25, 25))
        );

        Buttons3.setBackground(new java.awt.Color(231, 232, 248));
        Buttons3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buttons3.setPreferredSize(new java.awt.Dimension(235, 184));
        Buttons3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buttons3MouseClicked(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_return_book_125px.png"))); // NOI18N

        LB4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LB4.setForeground(new java.awt.Color(0, 102, 204));
        LB4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB4.setText("TABEL");

        javax.swing.GroupLayout Buttons3Layout = new javax.swing.GroupLayout(Buttons3);
        Buttons3.setLayout(Buttons3Layout);
        Buttons3Layout.setHorizontalGroup(
            Buttons3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buttons3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buttons3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB4, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addContainerGap())
        );
        Buttons3Layout.setVerticalGroup(
            Buttons3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Buttons3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB4)
                .addGap(15, 15, 15))
        );

        Buttons4.setBackground(new java.awt.Color(231, 232, 248));
        Buttons4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buttons4.setPreferredSize(new java.awt.Dimension(235, 184));
        Buttons4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buttons4MouseClicked(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_user_125px_1.png"))); // NOI18N

        LB1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LB1.setForeground(new java.awt.Color(0, 102, 204));
        LB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB1.setText("PROFIL");

        javax.swing.GroupLayout Buttons4Layout = new javax.swing.GroupLayout(Buttons4);
        Buttons4.setLayout(Buttons4Layout);
        Buttons4Layout.setHorizontalGroup(
            Buttons4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buttons4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buttons4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(LB1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addContainerGap())
        );
        Buttons4Layout.setVerticalGroup(
            Buttons4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Buttons4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LB1)
                .addGap(27, 27, 27))
        );

        Buttons5.setBackground(new java.awt.Color(231, 232, 248));
        Buttons5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buttons5.setPreferredSize(new java.awt.Dimension(235, 184));
        Buttons5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buttons5MouseClicked(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_team_125px.png"))); // NOI18N

        LB2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LB2.setForeground(new java.awt.Color(0, 102, 204));
        LB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB2.setText("TAMBAH DATA GURU");

        javax.swing.GroupLayout Buttons5Layout = new javax.swing.GroupLayout(Buttons5);
        Buttons5.setLayout(Buttons5Layout);
        Buttons5Layout.setHorizontalGroup(
            Buttons5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buttons5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buttons5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addContainerGap())
        );
        Buttons5Layout.setVerticalGroup(
            Buttons5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Buttons5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB2)
                .addGap(25, 25, 25))
        );

        Buttons6.setBackground(new java.awt.Color(231, 232, 248));
        Buttons6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buttons6.setPreferredSize(new java.awt.Dimension(235, 184));
        Buttons6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buttons6MouseClicked(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_chart_125px_1.png"))); // NOI18N

        LB5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LB5.setForeground(new java.awt.Color(0, 102, 204));
        LB5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB5.setText("GRAFIK");

        javax.swing.GroupLayout Buttons6Layout = new javax.swing.GroupLayout(Buttons6);
        Buttons6.setLayout(Buttons6Layout);
        Buttons6Layout.setHorizontalGroup(
            Buttons6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buttons6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buttons6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(LB5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Buttons6Layout.setVerticalGroup(
            Buttons6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Buttons6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LB5)
                .addGap(20, 20, 20))
        );

        Buttons7.setBackground(new java.awt.Color(231, 232, 248));
        Buttons7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buttons7.setPreferredSize(new java.awt.Dimension(235, 184));
        Buttons7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buttons7MouseClicked(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_student_male_125px.png"))); // NOI18N

        LB3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LB3.setForeground(new java.awt.Color(0, 102, 204));
        LB3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB3.setText("TAMBAH DATA SISWA");

        javax.swing.GroupLayout Buttons7Layout = new javax.swing.GroupLayout(Buttons7);
        Buttons7.setLayout(Buttons7Layout);
        Buttons7Layout.setHorizontalGroup(
            Buttons7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buttons7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buttons7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(LB3, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addContainerGap())
        );
        Buttons7Layout.setVerticalGroup(
            Buttons7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Buttons7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB3)
                .addGap(49, 49, 49))
        );

        Buttons8.setBackground(new java.awt.Color(231, 232, 248));
        Buttons8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buttons8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buttons8MouseClicked(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_settings_125px.png"))); // NOI18N

        LB6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LB6.setForeground(new java.awt.Color(0, 102, 204));
        LB6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB6.setText("SETTINGS");

        javax.swing.GroupLayout Buttons8Layout = new javax.swing.GroupLayout(Buttons8);
        Buttons8.setLayout(Buttons8Layout);
        Buttons8Layout.setHorizontalGroup(
            Buttons8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buttons8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buttons8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(LB6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Buttons8Layout.setVerticalGroup(
            Buttons8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Buttons8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(8, 8, 8)
                .addComponent(LB6)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Buttons4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buttons3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Buttons6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buttons5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Buttons7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buttons8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Buttons4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Buttons7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Buttons5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Buttons3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buttons6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buttons8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(970, 677));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        ImageIcon A = new ImageIcon(getClass().getResource("Images/close_window_30px.png"));
        Exit.setIcon(A);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        ImageIcon A = new ImageIcon(getClass().getResource("Images/icons8_close_window_30px_9.png"));
        Exit.setIcon(A);
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseEntered
        // TODO add your handling code here:
        ImageIcon A = new ImageIcon(getClass().getResource("Images/icons8_minimize_window_30px_2.png"));
        Minimize.setIcon(A);
    }//GEN-LAST:event_MinimizeMouseEntered

    private void MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseExited
        // TODO add your handling code here:
        ImageIcon A = new ImageIcon(getClass().getResource("Images/icons8_minimize_window_30px_1.png"));
        Minimize.setIcon(A);
    }//GEN-LAST:event_MinimizeMouseExited

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void OutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OutMouseExited
        // TODO add your handling code here:
        Out.setForeground(Color.white);
    }//GEN-LAST:event_OutMouseExited

    private void OutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OutMouseEntered
        // TODO add your handling code here:
        Out.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_OutMouseEntered

    private void OutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OutMouseClicked
         // TODO add your handling code here:
            Work AA = new Work();
            AA.show();
            dispose();
            A.show(false);
            B.show(false);
            C.show(false);
            D.show(false);
            E.show(false);
            F.show(false);
    }//GEN-LAST:event_OutMouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                String a,b,c,d,e,f,A;
            A = Fields.getText().toLowerCase();
            a = LB1.getText().toLowerCase();
            b = LB2.getText().toLowerCase();
            c = LB3.getText().toLowerCase();
            d = LB4.getText().toLowerCase();
            e = LB5.getText().toLowerCase();
            f = LB6.getText().toLowerCase();
            String etc = "guru";
            String etcs = "siswa";
            String exit = "keluar";
            String mini = "mini";
            
            System.out.println(A);
            
            if(A.equalsIgnoreCase(a)){
                LB1.setForeground(Color.GREEN);
                LB1();
                Fields.setText(null);
            }else if(A.equalsIgnoreCase(b)  || A.equalsIgnoreCase(etc)){
                LB2.setForeground(Color.GREEN);
                LB2();
                Fields.setText(null);
            }else if(A.equalsIgnoreCase(c) || A.equalsIgnoreCase(etcs)){
                LB3.setForeground(Color.GREEN);
                LB3();
                Fields.setText(null);
            }else if(A.equalsIgnoreCase(d)){
                LB4.setForeground(Color.GREEN);
                LB4();
                Fields.setText(null);
            }else if(A.equalsIgnoreCase(e)){
                LB5.setForeground(Color.GREEN);
                LB5();
                Fields.setText(null);
            }else if(A.equalsIgnoreCase(f)){
                LB6.setForeground(Color.GREEN);
                LB6();
                Fields.setText(null);
            }else if(A.equalsIgnoreCase(exit)){
                 System.exit(0);
                 Fields.setText(null);
            }else if(A.equalsIgnoreCase(mini)){
                this.setExtendedState(JFrame.ICONIFIED);
                Fields.setText(null);
            }
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String a,b,c,d,e,f,A;
            A = Fields.getText().toLowerCase();
            a = LB1.getText().toLowerCase();
            b = LB2.getText().toLowerCase();
            c = LB3.getText().toLowerCase();
            d = LB4.getText().toLowerCase();
            e = LB5.getText().toLowerCase();
            f = LB6.getText().toLowerCase();
            String etc = "guru";
            String etcs = "siswa";
            String exit = "keluar";
            String mini = "mini";
            
            System.out.println(A);
            
            if(A.equalsIgnoreCase(a)){
                LB1.setForeground(Color.GREEN);
                LB1();
                Fields.setText(null);
            }else if(A.equalsIgnoreCase(b) || A.equalsIgnoreCase(etc)){
                LB2.setForeground(Color.GREEN);
                LB2();
                Fields.setText(null);
            }else if(A.equalsIgnoreCase(c) || A.equalsIgnoreCase(etcs)){
                LB3.setForeground(Color.GREEN);
                LB3();
                Fields.setText(null);
            }else if(A.equalsIgnoreCase(d)){
                LB4.setForeground(Color.GREEN);
                LB4();
                Fields.setText(null);
            }else if(A.equalsIgnoreCase(e)){
                LB5.setForeground(Color.GREEN);
                LB5();
                Fields.setText(null);
            }else if(A.equalsIgnoreCase(f)){
                LB6.setForeground(Color.GREEN);
                LB6();
                Fields.setText(null);
            }else if(A.equalsIgnoreCase(exit)){
                 System.exit(0);
                 Fields.setText(null);
            }else if(A.equalsIgnoreCase(mini)){
                this.setExtendedState(JFrame.ICONIFIED);
                Fields.setText(null);
            }        
    }//GEN-LAST:event_jButton1MouseClicked

    private void Buttons8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buttons8MouseClicked
        // TODO add your handling code here:
        A.show();
    }//GEN-LAST:event_Buttons8MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        mousexdrag = evt.getX();
        mouseydrag = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - mousexdrag, y - mouseydrag);
        System.out.println(x + "," + y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void Buttons3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buttons3MouseClicked
        // TODO add your handling code here:
        B.show();
    }//GEN-LAST:event_Buttons3MouseClicked

    private void Buttons5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buttons5MouseClicked
        // TODO add your handling code here:
        C.show();
    }//GEN-LAST:event_Buttons5MouseClicked

    private void Buttons7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buttons7MouseClicked
        // TODO add your handling code here:
        D.show();
    }//GEN-LAST:event_Buttons7MouseClicked

    private void Buttons6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buttons6MouseClicked
        // TODO add your handling code here:
        E.show();
    }//GEN-LAST:event_Buttons6MouseClicked

    private void Buttons4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buttons4MouseClicked
        // TODO add your handling code here:
        F.show();
    }//GEN-LAST:event_Buttons4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buttons3;
    private javax.swing.JPanel Buttons4;
    private javax.swing.JPanel Buttons5;
    private javax.swing.JPanel Buttons6;
    private javax.swing.JPanel Buttons7;
    public javax.swing.JPanel Buttons8;
    private javax.swing.JLabel Exit;
    private javax.swing.JTextField Fields;
    private javax.swing.JLabel LB1;
    private javax.swing.JLabel LB2;
    private javax.swing.JLabel LB3;
    private javax.swing.JLabel LB4;
    private javax.swing.JLabel LB5;
    private javax.swing.JLabel LB6;
    private javax.swing.JLabel LBL;
    private javax.swing.JLabel Minimize;
    public javax.swing.JLabel Name;
    private javax.swing.JLabel Out;
    public javax.swing.JPanel Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images/icons8_news_10px.png")));
    }
}
