/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dwi Rifki Novianto
 */
public class ProfilTeacher extends javax.swing.JFrame {
     String level = session.get_Level();
     int mousexdrag, mouseydrag;
     String A, B, C, D, E, F, G;
     Connection conn;
     PreparedStatement pst;
     ResultSet rs;

    /**
     * Creates new form Profile
     */
    public ProfilTeacher() {
        initComponents();
        Names.setEnabled(false);
        Codes.setEnabled(false);
        Subjects.setEnabled(false);
        Emails.setEnabled(false);
        HPs.setEnabled(false);
        Address.setEnabled(false);
        setIcon();
         try {
             showUpS();
         } catch (SQLException ex) {
             Logger.getLogger(ProfilTeacher.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    public void showUpS() throws SQLException{
        String SQL = "SELECT * FROM data_teacher WHERE code = '"+ level +"'";
       java.sql.Connection conn = Connections.getConnection();
       java.sql.Statement pst = conn.createStatement();
       java.sql.ResultSet rs = pst.executeQuery(SQL);
    
        if(rs.next()){
            A = rs.getString("code");
            B = rs.getString("name");
            C = rs.getString("subject");
            D = rs.getString("handphone");
            E = rs.getString("email");
            F = rs.getString("address");
            
        Names.setText(B);
        Codes.setText(A);
        Subjects.setText(C);
        Emails.setText(D);
        HPs.setText(E);
        Address.setText(F);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panels = new javax.swing.JPanel();
        PanelA = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelB = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Names = new javax.swing.JTextField();
        Codes = new javax.swing.JTextField();
        Emails = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        HPs = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Subjects = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Profil");
        setUndecorated(true);
        setResizable(false);

        Panels.setBackground(new java.awt.Color(255, 255, 255));
        Panels.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Panels.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelsMouseDragged(evt);
            }
        });
        Panels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelsMousePressed(evt);
            }
        });
        Panels.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelA.setBackground(new java.awt.Color(0, 102, 255));
        PanelA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_admin_settings_male_90px.png"))); // NOI18N
        PanelA.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROFIL ADMIN");
        PanelA.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 190, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_undo_50px.png"))); // NOI18N
        jLabel3.setText(" KELUAR");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        PanelA.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 180, 100));

        Panels.add(PanelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 100));

        PanelB.setBackground(new java.awt.Color(255, 255, 255));
        PanelB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        PanelB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATA PROFIL GURU");
        PanelB.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 23, 748, 55));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("MATA PELAJARAN");
        PanelB.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, 29));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("NAMA LENGKAP");
        PanelB.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 110, 29));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("KODE");
        PanelB.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 110, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("E-MAIL");
        PanelB.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 110, 30));

        Names.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Names.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Names.setDisabledTextColor(new java.awt.Color(0, 102, 204));
        PanelB.add(Names, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 300, 30));

        Codes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Codes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Codes.setDisabledTextColor(new java.awt.Color(0, 102, 204));
        PanelB.add(Codes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 300, 30));

        Emails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Emails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Emails.setDisabledTextColor(new java.awt.Color(0, 102, 204));
        PanelB.add(Emails, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 300, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("ALAMAT");
        PanelB.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 110, 30));

        HPs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HPs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        HPs.setDisabledTextColor(new java.awt.Color(0, 102, 204));
        PanelB.add(HPs, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 300, 30));

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Bila terjadi kesalahan dalam pendataan, harap hubungi Admin !!!");
        PanelB.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 470, 20));

        Subjects.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Subjects.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Subjects.setDisabledTextColor(new java.awt.Color(0, 102, 204));
        PanelB.add(Subjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 300, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("NO HP");
        PanelB.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 110, 30));

        Address.setColumns(20);
        Address.setRows(5);
        jScrollPane1.setViewportView(Address);

        PanelB.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 300, 90));

        Panels.add(PanelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 770, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panels, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(770, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void PanelsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelsMousePressed
        // TODO add your handling code here:
        mousexdrag = evt.getX();
        mouseydrag = evt.getY();
    }//GEN-LAST:event_PanelsMousePressed

    private void PanelsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelsMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - mousexdrag, y - mouseydrag);
    }//GEN-LAST:event_PanelsMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfilTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Address;
    private javax.swing.JTextField Codes;
    private javax.swing.JTextField Emails;
    private javax.swing.JTextField HPs;
    private javax.swing.JTextField Names;
    private javax.swing.JPanel PanelA;
    private javax.swing.JPanel PanelB;
    private javax.swing.JPanel Panels;
    private javax.swing.JTextField Subjects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
      
    
    public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images/icons8_news_10px.png")));
    }

}
