/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ACER
 */
public class SettingsTeacher extends javax.swing.JFrame {
    int mousexdrag;
    int mouseydrag;
    java.sql.Connection conn = null;
    java.sql.PreparedStatement pst = null;
    java.sql.ResultSet rs = null;

    String log_id = session.get_log_id();
    
    SettingsTeacher(){
        initComponents();
        UsernameA.setText(log_id);
        UsernameA.setEnabled(false);
        setIcon();
    }
    
    /**
     * Creates new form Settings
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Panels = new javax.swing.JPanel();
        Panels3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Panel4 = new javax.swing.JPanel();
        labels = new javax.swing.JLabel();
        PanelC = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        UsernameA = new javax.swing.JTextField();
        Password2A = new javax.swing.JPasswordField();
        PasswordA = new javax.swing.JPasswordField();
        Button3 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        IdA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings ");
        setAutoRequestFocus(false);
        setUndecorated(true);

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        Panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelMouseDragged(evt);
            }
        });
        Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelMousePressed(evt);
            }
        });
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panels.setBackground(new java.awt.Color(153, 153, 153));
        Panels.setForeground(new java.awt.Color(255, 255, 255));
        Panels.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panels3.setBackground(new java.awt.Color(51, 51, 51));
        Panels3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panels3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panels3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panels3MouseExited(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_home_60px.png"))); // NOI18N

        javax.swing.GroupLayout Panels3Layout = new javax.swing.GroupLayout(Panels3);
        Panels3.setLayout(Panels3Layout);
        Panels3Layout.setHorizontalGroup(
            Panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panels3Layout.setVerticalGroup(
            Panels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panels3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        Panels.add(Panels3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 70, 360));

        Panel4.setBackground(new java.awt.Color(51, 51, 51));
        Panel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel4MouseExited(evt);
            }
        });

        labels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labels.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Images/icons8_delete_40px.png"))); // NOI18N

        javax.swing.GroupLayout Panel4Layout = new javax.swing.GroupLayout(Panel4);
        Panel4.setLayout(Panel4Layout);
        Panel4Layout.setHorizontalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labels, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        Panel4Layout.setVerticalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labels, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Panels.add(Panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 90));

        Panel.add(Panels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 450));

        PanelC.setBackground(new java.awt.Color(0, 102, 204));
        PanelC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CHANGE PASSWORD");
        PanelC.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 570, 60));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Masukan Password Baru");
        PanelC.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 170, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Masukan Username");
        PanelC.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 170, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Masukan Password Lama");
        PanelC.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 170, -1));

        UsernameA.setBackground(new java.awt.Color(0, 102, 204));
        UsernameA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UsernameA.setForeground(new java.awt.Color(255, 255, 255));
        UsernameA.setBorder(null);
        UsernameA.setCaretColor(new java.awt.Color(255, 255, 255));
        UsernameA.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        PanelC.add(UsernameA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 250, 35));

        Password2A.setBackground(new java.awt.Color(0, 102, 204));
        Password2A.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Password2A.setForeground(new java.awt.Color(255, 255, 255));
        Password2A.setBorder(null);
        Password2A.setCaretColor(new java.awt.Color(255, 255, 255));
        PanelC.add(Password2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 250, 35));

        PasswordA.setBackground(new java.awt.Color(0, 102, 204));
        PasswordA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PasswordA.setForeground(new java.awt.Color(255, 255, 255));
        PasswordA.setBorder(null);
        PasswordA.setCaretColor(new java.awt.Color(255, 255, 255));
        PanelC.add(PasswordA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 250, 35));

        Button3.setBackground(new java.awt.Color(0, 204, 0));
        Button3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button3.setForeground(new java.awt.Color(255, 255, 255));
        Button3.setText("BUAT ACCOUNT");
        Button3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        Button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button3MouseClicked(evt);
            }
        });
        PanelC.add(Button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 250, 40));
        PanelC.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 250, -1));
        PanelC.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 250, 10));
        PanelC.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 250, 10));
        PanelC.add(IdA, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 50, 20));

        Panel.add(PanelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 660, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(725, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Panels3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panels3MouseEntered
        // TODO add your handling code here:
        Panels3.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_Panels3MouseEntered

    private void Panels3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panels3MouseExited
        // TODO add your handling code here:
        Panels3.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_Panels3MouseExited

    private void Panel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel4MouseEntered
        // TODO add your handling code here:
        Panel4.setBackground(new Color(102,102,102));
        ImageIcon A = new ImageIcon(getClass().getResource("Images/icons8_delete_40px_4.png"));
        labels.setIcon(A);
    }//GEN-LAST:event_Panel4MouseEntered

    private void Panel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel4MouseExited
        // TODO add your handling code here:
        Panel4.setBackground(new Color (51,51,51));
        ImageIcon A = new ImageIcon(getClass().getResource("Images/icons8_delete_40px_3.png"));
        labels.setIcon(A);
    }//GEN-LAST:event_Panel4MouseExited

    private void Panel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel4MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Panel4MouseClicked

    private void PanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMousePressed
        // TODO add your handling code here:
        mousexdrag = evt.getX();
        mouseydrag = evt.getY();
    }//GEN-LAST:event_PanelMousePressed

    private void PanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - mousexdrag,y - mouseydrag);
        System.out.println(x + "," + y);
    }//GEN-LAST:event_PanelMouseDragged

    private void Button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button3MouseClicked
        // TODO add your handling code here:
        try{
         String AAA, BCA, CCC;
            AAA = UsernameA.getText();
            BCA = PasswordA.getText();
            CCC = Password2A.getText();
            
            String SQL = "SELECT * FROM sign_in WHERE username = ? and password = ?";
            conn = Connections.getConnection();
            pst = conn.prepareStatement(SQL);
            pst.setString(1, AAA);
            pst.setString(2, BCA);
            rs = pst.executeQuery();
            
            if(rs.next()){
            String Local, Pass;
            Local = rs.getString("type");
            Pass = rs.getString("password");
            if(Local.equalsIgnoreCase("guru") && BCA.equals(Pass)){
            String SQL1 = 
            "UPDATE sign_in SET username = username ,password='" + CCC + "', NISN = NISN, email = email ,  type = type WHERE username = '"+ AAA +"'";
            conn = Connections.getConnection();
            pst = conn.prepareStatement(SQL1);
            pst.execute(SQL1);
            new Congrats().show();
            
            }else{
              new Errors().show();
            }
            
            }else{
              new Error().show();  
        }
            
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_Button3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button3;
    private javax.swing.JLabel IdA;
    public javax.swing.JPanel Panel;
    public javax.swing.JPanel Panel4;
    private javax.swing.JPanel PanelC;
    private javax.swing.JPanel Panels;
    private javax.swing.JPanel Panels3;
    private javax.swing.JPasswordField Password2A;
    private javax.swing.JPasswordField PasswordA;
    public javax.swing.JTextField UsernameA;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel labels;
    // End of variables declaration//GEN-END:variables
   public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images/icons8_news_10px.png")));
    }


}
